# Generated by Django 4.2 on 2025-01-24 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keiziban', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articale',
            new_name='Article',
        ),
    ]
